services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: cityZookeeper
    ports:
      - "2181:2181"

  kafka:
      image: wurstmeister/kafka
      container_name: cityKafka
      ports:
        - "9092:9092"
      hostname: kafka
      environment:
        KAFKA_ADVERTISED_HOST_NAME: kafka
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_PORT: 9092
      links:
        - zookeeper

  mysql:
    image: mysql:8.0
    container_name: cityMysqldb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: pedidos
      MYSQL_USER: citydb
      MYSQL_PASSWORD: pass
    volumes:
      - mysql_data:/var/lib/mysql

  consumer:
    build: ./consumer
    container_name: cityConsumer
    ports:
      - "8090:8090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/pedidos
      SPRING_DATASOURCE_USERNAME: citydb
      SPRING_DATASOURCE_PASSWORD: pass
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - mysql
      - kafka

  producer:
    build: ./productor
    container_name: cityProductor
    ports:
      - "8080:8080"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka

volumes:
  mysql_data: