version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysqldbCliente
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: pedidos
      MYSQL_USER: citydb
      MYSQL_PASSWORD: pass
    volumes:
      - mysq_data:/var/lib/mysql

  consumer:
      build: ./consumer
      ports:
        - "8090:8090"
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/pedidos
        SPRING_DATASOURCE_USERNAME: citydb
        SPRING_DATASOURCE_PASSWORD: pass
      depends_on:
        - mysql

  producer:
      build: ./productor
      ports:
        - "8080:8080"
      depends_on:
        - mysql

volumes:
  mysql_data: